<template>
  <section>
    <div class="list-container">
      <transition-group name="list">
        <div class="group-preview-wrapper" v-for="group in groups" :key="group._id">
          <!-- <el-button type="success" @click="$emit('delete' , group._id)">Delete</el-button> -->
          <!-- <router-link :to="'/group/edit/' + group._id">
            <el-button type="danger">Edit</el-button>
          </router-link>-->
          <router-link :to="'/groups/' + group._id">
            <GroupPreview :group="group"></GroupPreview>
          </router-link>
          <!-- class="slide-in-fwd-bottom" -->
        </div>
      </transition-group>
    </div>
  </section>
</template>

<script>
import GroupPreview from "./group-preview-cmp.vue";
export default {
  props: {
    groups: {
      type: Array,
      required: true,
      default: function() {
        return "EMPTY";
      }
    }
  },
  components: {
    GroupPreview
  }
};
</script>

<style scoped lang="scss">

section {
  // margin-top: 100px;

  display: flex;
  justify-content: center;
  align-items: center;

  .list-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    width: 100%;
  }
  .group-preview-wrapper {
    display: inline-block;
  }
}
.slide-in-fwd-bottom {
  -webkit-animation: slide-in-fwd-bottom 0.4s
    cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-fwd-bottom 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-3-27 17:46:59
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-fwd-bottom {
  0% {
    -webkit-transform: translateZ(-1400px) translateY(800px);
    transform: translateZ(-1400px) translateY(800px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-fwd-bottom {
  0% {
    -webkit-transform: translateZ(-1400px) translateY(800px);
    transform: translateZ(-1400px) translateY(800px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
    transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
</style>
